server:
  port: 8083

spring:
  cloud:
    stream:
      bindings:
        smsVerificationMessagePublish:
          destination: sms-verification-message
        smsVerificationDeliveredSubscribe:
          destination: sms-verification-delivered
          group: sms-verification